# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/test/TestCanonicalXML.cpp) \
                 $$quote($$BASEDIR/src/test/TestDNS.cpp) \
                 $$quote($$BASEDIR/src/test/TestICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocketLoopback.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPListener.cpp) \
                 $$quote($$BASEDIR/src/test/TestSTUNDiscovery.cpp) \
                 $$quote($$BASEDIR/src/test/TestTURNSocket.cpp) \
                 $$quote($$BASEDIR/src/test/boost_replacement.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.h) \
                 $$quote($$BASEDIR/src/test/boost_replacement.h) \
                 $$quote($$BASEDIR/src/test/config.h)

    }

    CONFIG(release, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/test/TestCanonicalXML.cpp) \
                 $$quote($$BASEDIR/src/test/TestDNS.cpp) \
                 $$quote($$BASEDIR/src/test/TestICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocketLoopback.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPListener.cpp) \
                 $$quote($$BASEDIR/src/test/TestSTUNDiscovery.cpp) \
                 $$quote($$BASEDIR/src/test/TestTURNSocket.cpp) \
                 $$quote($$BASEDIR/src/test/boost_replacement.cpp) \
                 $$quote($$BASEDIR/src/test/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.h) \
                 $$quote($$BASEDIR/src/test/boost_replacement.h) \
                 $$quote($$BASEDIR/src/test/config.h)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/cryptopp) \
                 $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-core) \
                 $$quote(../../../../op/hookflash-libs/bbBoost) \
                 $$quote(../../../../op/hookflash-libs/udns)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/test/TestCanonicalXML.cpp) \
                 $$quote($$BASEDIR/src/test/TestDNS.cpp) \
                 $$quote($$BASEDIR/src/test/TestICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocket.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPICESocketLoopback.cpp) \
                 $$quote($$BASEDIR/src/test/TestRUDPListener.cpp) \
                 $$quote($$BASEDIR/src/test/TestSTUNDiscovery.cpp) \
                 $$quote($$BASEDIR/src/test/TestTURNSocket.cpp) \
                 $$quote($$BASEDIR/src/test/boost_replacement.cpp) \
                 $$quote($$BASEDIR/src/test/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.h) \
                 $$quote($$BASEDIR/src/test/boost_replacement.h) \
                 $$quote($$BASEDIR/src/test/config.h)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/test) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}.ts)

