# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestHelper.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestIPAddress.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestNumeric.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxy.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxyUsingGUIThread.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocket.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocketAsync.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestString.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestStringize.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestTimer.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestXML.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.h)

    }

    CONFIG(release, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestHelper.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestIPAddress.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestNumeric.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxy.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxyUsingGUIThread.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocket.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocketAsync.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestString.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestStringize.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestTimer.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestXML.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.h)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        INCLUDEPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        DEPENDPATH +=  $$quote(../../../../op/hookflash-libs/zsLib) \
                 $$quote(../../../../op/hookflash-libs/bbBoost)

        SOURCES +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestHelper.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestIPAddress.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestNumeric.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxy.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestProxyUsingGUIThread.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocket.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestSocketAsync.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestString.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestStringize.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestTimer.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/TestXML.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.cpp) \
                 $$quote($$BASEDIR/src/zsLibTest/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/QtCrossThreadNotifier.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/zsLibTest/boost_replacement.h)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/zsLibTest) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}.ts)

